### ISSUE TITLE
JavaScript formatter stopped working

### ISSUE THREAD

**Issue by levz0r** [Unibeautify/vscode#102]
Hi,
Since v0.6.0, the prettier formatter doesn't format javascript files anymore.
.unibeautifyrc.json:
```
{
  "JavaScript": {
    "beautifiers": ["Prettier"],
    "indent_style": "space",
    "indent_size": 2
  }
}
```
package.json:
```
"devDependencies": {
    "@unibeautify/beautifier-js-beautify": "^0.3.2",
    "@unibeautify/beautifier-prettier": "^0.8.0",
    "js-beautify": "^1.7.5",
    "prettier": "^1.14.0",
    "unibeautify": "^0.15.0"
  }
```
Any ideas?

**Comment by szeck87** [comment]
We fixed a bug where the extension wasn't being sent to the `beautify` method properly (#95).  Now that we are doing that, when sending files with a language name of "JavaScript" and extension `.js`, it uses JSX, probably because our languages metadata has `.js` as an extension for JavaScript files:  https://github.com/Unibeautify/unibeautify/blob/master/src/languages.json#L3594.

@Glavin001 we should fine tune the `findLanguages` method to be more precise since we are always using the [first language](https://github.com/Unibeautify/unibeautify/blob/master/src/LanguageManager.ts#L20) in the returned array.

**Comment by szeck87** [comment]
@levz0r this should be fixed with the 0.6.1 release.  Please let us know if you have issues after updating.

**Comment by levz0r** [comment]
@szeck87 thank you for the prompt fix!
Unfortunately, I am unable to update the extension (I don't know if it is related to the updated version).
Here's the output when running: `code --install-extension Glavin001.unibeautify-vscode`
```
Error: Invalid package C:\Users\(me)\.vscode\extensions\.glavin001.unibeautify-vscode-0.6.1\.vscode-test\stable\Visual Studio Code.app\Contents\Resources\app\node_modules.asar
    at invalidArchiveError (ELECTRON_ASAR.js:154:19)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:210:16)
    at WriteStream.open (fs.js:2043:6)
    at new WriteStream (fs.js:2029:10)
    at Object.fs.createWriteStream (fs.js:1991:10)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:238
    at new n.Class.derive._oncancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:55:378)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:204
    at Object.v [as _notify] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:48:572)
    at Object.enter (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:51:924)
    at n.Class.derive._oncancel._run (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:53:719)
    at n.Class.derive._oncancel._completed (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:53:160)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:84:295
    at FSReqWrap.oncomplete (fs.js:114:15)
    at Timeout._onTimeout (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:65:18)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by Glavin001** [comment]
> Unibeautify ignoring .unibeautifyrc.json when formatting .jsx file but works as expected when formatting .js file.
>
> `unibeautifyrc.json`
> 
> ```
> {
>    "JavaScript": {
>        "beautifiers": ["Prettier"],
>        "quotes": "single"
>    }
> }
>```

@mmn6d6d6e It sounds like you need to add `JSX` in your enabled languages as well as your existing `JavaScript` language. Something like:

```json
{
    "JSX": {
        "beautifiers": ["Prettier"],
        "quotes": "single"
    },
    "JavaScript": {
        "beautifiers": ["Prettier"],
        "quotes": "single"
    }
}
```

See https://unibeautify.com/docs/language-jsx.html for more information on JSX language support.

**Comment by mmn6d6d6e** [comment]
@Glavin001

It's been a while since I working on JavaScript/ReactJS related project. Last time, if I remember correctly, `.jsx` was not handled correctly yet by Unibeautify, so I made some workaround by adding this on setting:
```
"files.associations": {
    "*.js": "javascript",
    "*.jsx": "javascript"
},
```
Which makes Unibeautify treat `.jsx` files as regular `.js` files.

So, by removing that setting and adding `JSX` as enabled language, now Unibeautify is working correctly! 
Thx!

**Comment by Glavin001** [comment]
🎉 Awesome to hear, @mmn6d6d6e !
